export declare const noop: () => void;
export declare const isUndefined: (v: any) => v is undefined;
export declare const isFunction: (v: any) => v is Function;
export declare const hasWindow: () => boolean;
export declare const hasDocument: () => boolean;
export declare const isOnline: () => boolean;
export declare const isVisible: () => boolean;
export declare const isActive: () => boolean;
export declare const initFocus: (cb: () => void) => () => void;
export declare const initReconnect: (cb: () => void) => () => void;
